ALTER TABLE "treatments" ADD COLUMN "description" text DEFAULT '' NOT NULL;--> statement-breakpoint
ALTER TABLE "treatments" ADD COLUMN "image_alt" text DEFAULT '' NOT NULL;--> statement-breakpoint
ALTER TABLE "treatments" ADD COLUMN "image_storage_path" text;--> statement-breakpoint
ALTER TABLE "treatments" ADD COLUMN "featured" boolean DEFAULT false NOT NULL;--> statement-breakpoint
ALTER TABLE "treatments" ADD COLUMN "sort_order" integer DEFAULT 0 NOT NULL;--> statement-breakpoint
UPDATE "treatments" SET "description" = 'Klassisk herreklip med saks og maskine, afsluttet med styling.', "image" = '/images/services/herreklip-customer.webp', "image_alt" = 'Kunde med færdig klassisk herreklip', "featured" = true, "sort_order" = 0 WHERE "id" = 'herreklip';--> statement-breakpoint
UPDATE "treatments" SET "description" = 'Trimning og formning af skæg, så linjerne står skarpt.', "image" = '/images/services/skaegtrimning-customer.webp', "image_alt" = 'Kunde med færdigtrimmet og formet skæg', "featured" = true, "sort_order" = 0 WHERE "id" = 'skaeg';--> statement-breakpoint
UPDATE "treatments" SET "description" = 'Komplet behandling med klipning, skægtrimning og skarpe kanter.', "image" = '/images/services/herreklip-og-skaeg-customer.webp', "image_alt" = 'Kunde med frisk herreklip og formet skæg', "featured" = true, "sort_order" = 1 WHERE "id" = 'haar-og-skaeg';--> statement-breakpoint
UPDATE "treatments" SET "description" = 'Rolig og grundig klipning til pensionister med fokus på et pænt, naturligt resultat.', "image" = '/images/services/pensionistklip-customer.webp', "image_alt" = 'Ældre kunde med færdig klassisk klipning og sølvgråt hår', "sort_order" = 2 WHERE "id" = 'pensionist';--> statement-breakpoint
UPDATE "treatments" SET "description" = 'Klassisk pensionistklip udført med saks for et naturligt resultat.', "image" = '/images/services/pensionist-saks-customer-v2.jpg', "image_alt" = 'Pensionist med klassisk sakseklip', "sort_order" = 3 WHERE "id" = 'pensionist-med-saks';--> statement-breakpoint
UPDATE "treatments" SET "description" = 'Ensartet, kort klipning med maskine.', "image" = '/images/services/maskineklip-customer-v2.jpg', "image_alt" = 'Kunde med kort maskineklip', "sort_order" = 4 WHERE "id" = 'maskineklip';--> statement-breakpoint
UPDATE "treatments" SET "description" = 'Tryg og rolig klipning for børn under 10 år.', "image" = '/images/services/boerneklip-customer-v2.jpg', "image_alt" = 'Barn med færdig børneklipning', "sort_order" = 5 WHERE "id" = 'boerneklip-under-10';--> statement-breakpoint
UPDATE "treatments" SET "description" = 'Præcis hårfjerning med voks og tråd.', "image" = '/images/services/haarfjerning-voks-traad-customer-v2.jpg', "image_alt" = 'Hårfjerning med tråd', "sort_order" = 0 WHERE "id" = 'haarfjerning-voks-traad';
